In [1]:
# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import gmaps
import os
import json
from pprint import pprint

from api_keys import g_key

### Store Part I results into DataFrame
* Load the csv exported in Part I to a DataFrame

In [2]:
output_data_file = "weather_data.csv"
# output_data_file

types_df = pd.read_csv(output_data_file)

weather_data = types_df.drop(columns=["Unnamed: 0"])
weather_data

,City,Country,Date,Latitude,Longitude,Max Temperature,Humidity,Cloudiness,Wind Speed
0,Narsaq,GL,1589910035,60.92,-46.05,55.40,19,20,11.41
1,Ushuaia,AR,1589910035,-54.80,-68.30,42.80,81,75,26.40
2,Rocha,UY,1589909945,-34.48,-54.33,72.61,63,3,8.63
3,Atuona,PF,1589910035,-9.80,-139.03,80.91,75,1,15.37
4,Rome,US,1589909883,43.21,-75.46,68.00,32,1,16.11
...,...,...,...,...,...,...,...,...,...
542,Urengoy,RU,1589910084,65.97,78.37,65.37,63,42,10.42
543,Astorga,BR,1589910084,-23.23,-51.67,82.40,39,20,11.41
544,Kyshtovka,RU,1589910084,56.55,76.63,62.33,80,66,7.27
545,Garoowe,SO,1589910084,8.41,48.48,92.57,36,60,14.76
546,El Tigre,VE,1589910084,8.89,-64.25,96.66,26,35,11.36

### Humidity Heatmap
* Configure gmaps.
* Use the Lat and Lng as locations and Humidity as the weight.
* Add Heatmap layer to map.

In [3]:
gmaps.configure(api_key=g_key)

In [4]:
#locations
locations = weather_data[["Latitude", "Longitude"]]
#humidity
humidity = weather_data["Humidity"].astype(float)

fig = gmaps.figure()

heatmap_layer = gmaps.heatmap_layer(locations, weights=humidity,
                                   dissipating=False, max_intensity=300,
                                   point_radius=5)

fig.add_layer(heatmap_layer)
fig

Figure(layout=FigureLayout(height='420px'))

### Create new DataFrame fitting weather criteria
* Narrow down the cities to fit weather conditions.
* Drop any rows will null values.

In [5]:
# A max temperature lower than 89 degrees but higher than 70.
# Wind speed less than 10 mph.
# Zero cloudiness.
# Drop any rows that don't contain all three conditions. 

new_types_df = pd.DataFrame(weather_data, columns = ["City", "Max Temperature", "Wind Speed", "Cloudiness"])

max_temp = (new_types_df["Max Temperature"] <= 89) & (new_types_df["Max Temperature"] > 70)
wind_speed = new_types_df["Wind Speed"] < 10
cloudiness = new_types_df["Cloudiness"] == 0

# new dataFrame
new_types_df[max_temp & wind_speed & cloudiness]

            City  Max Temperature  Wind Speed  Cloudiness
6         Castro            72.59        6.87           0
22       Kabinda            72.88        4.41           0
81     Daud Khel            85.68        3.13           0
93         Umluj            86.00        9.37           0
178         Auch            77.00        5.99           0
218   Mossamedes            78.91        6.49           0
296         Gaza            84.99        1.99           0
319       Chaman            73.26        1.21           0
336       Jiwani            86.47        5.41           0
380        Belen            86.00        8.05           0
386        Mahon            73.40        5.82           0
391      Iturama            81.10        6.78           0
428        Mahon            73.40        5.82           0
436       Bereda            82.00        4.00           0
443     Carballo            77.00        5.82           0
464  San Vicente            76.77        6.02           0
487    Dalbandin            85.39        7.81           0
507     Lianzhou            72.16        1.45           0
508    Mahajanga            75.20        4.70           0
531   Walvis Bay            86.00        8.05           0

### Hotel Map
* Store into variable named `hotel_df`.
* Add a "Hotel Name" column to the DataFrame.
* Set parameters to search for hotels with 5000 meters.
* Hit the Google Places API for each city's coordinates.
* Store the first Hotel result into the DataFrame.
* Plot markers on top of the heatmap.

In [6]:
hotel_df = pd.DataFrame(weather_data, columns=["City", "Country", "Latitude", "Longitude"])

hotel_df["Hotel Name"] = ""

hotel_df

          City Country  Latitude  Longitude Hotel Name
0       Narsaq      GL     60.92     -46.05
1      Ushuaia      AR    -54.80     -68.30
2        Rocha      UY    -34.48     -54.33
3       Atuona      PF     -9.80    -139.03
4         Rome      US     43.21     -75.46
..         ...     ...       ...        ...        ...
542    Urengoy      RU     65.97      78.37
543    Astorga      BR    -23.23     -51.67
544  Kyshtovka      RU     56.55      76.63
545    Garoowe      SO      8.41      48.48
546   El Tigre      VE      8.89     -64.25

[547 rows x 5 columns]

In [8]:
target_coordinates = f"{hotel_df['Latitude'][0]},{hotel_df['Longitude'][0]}"
target_search = "hotel"
target_radius = 5000
target_type = "hotel"

# set up a parameters dictionary
params = {
    "location": target_coordinates,
    "keyword": target_search,
    "radius": target_radius,
    "type": target_type,
    "key": g_key
}

# base url
base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"

# run a request using our params dictionary
response = requests.get(base_url, params=params)
#---------

hotel_name = []

# params dictionary to update each iteration
params = {"radius": 5000,"types": "hotel","keyword": "hotel","key": g_key}

# taken from Airpost_Ratings Example done in class
for index, row in hotel_df.iterrows():
    # get lat, lng from df
    latitude = row["Latitude"]
    longitude = row["Longitude"]

    # change location each iteration while leaving original params in place
    params["location"] = f"{latitude},{longitude}"

    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"

    # make request and print url
    name_address = requests.get(base_url, params=params)
    
    # convert to json
    name_address = name_address.json()
    # print(json.dumps(name_address, indent=4, sort_keys=True))
    try:
#         hotel_df.iloc[index, 4] = name_address['results'][0]['name']
        hotel_name.append(name_address['results'][0]['name'])
    except IndexError:
        hotel_name.append(np.nan)
        
hotel_name

['Igdlo Guesthouse',
 'Los Cauquenes Resort & Spa',
 'Beleza Pura B&B',
 'Simplicité Marquises',
 'Wingate By Wyndham Rome',
 'Mercure Bengkulu',
 'Central Palace Hotel - Castro (PR)',
 'Heritage Hotel',
 nan,
 nan,
 'Foveaux Hotel',
 'Byron Cove Beach House',
 nan,
 'Atlanticview Cape Town Boutique Hotel',
 'Kangcheng Jian Guo International Hotel',
 "Pension Maro'i",
 'Top of the World Hotel',
 'Hotel Isla Rey Jorge',
 'Hurtigruten Hus',
 'Villa Del Palmar Beach Resort & Spa Cabo San Lucas',
 'Coral Coast Tourist Park',
 nan,
 nan,
 'Quinta Das Buganvílias',
 'Hotel Hacienda de Abajo',
 'Maritim Crystals Beach Hotel Mauritius',
 nan,
 nan,
 nan,
 'Sails Port Macquarie by Rydges',
 nan,
 'Hotel Klaksvík',
 'Bohio Dive Resort',
 'Moss Hotel',
 'The Explorer Hotel',
 'Hoedjiesbaai Hotel',
 'Newport Central Hotel- Book Direct with Us',
 'Les Embruns Du Baril',
 'Tourist House - Sablino',
 nan,
 'Hotel Olako',
 'Best Western Kodiak Inn and Convention Center',
 'Broadwater Resort',
 'Kairos Cottage',
 'Blue Lagoon Hotel',
 'TDC Village (Hundred Man Camp)',
 'Hotel La Villa Couacou',
 nan,
 'Severnoye Zoloto',
 'Hotel - Restaurant Anno 1617',
 "Ellie's Villa",
 'The Edgewater Resort and Spa',
 'DoubleTree by Hilton Hotel Pune - Chinchwad',
 nan,
 'The Halyards Hotel',
 nan,
 'Radisson Blu Polar Hotel, Spitsbergen',
 'Blue Bell Inn',
 'Hotel Litu',
 '7 on Marine',
 'Hotell Frøya',
 'Hotel Azovskaya Rusalochka',
 'Isles Sunset Lodge',
 'Paradise First Hotel',
 'Hotel Apart',
 'Hotel Arctic',
 'Meieriet Restaurant',
 'Corrigans Cove Resort',
 'Coral Sea Resort & Casino',
 'Hilton Garden Inn Kauai Wailua Bay',
 'Hotel Kajaani',
 'Hotel Angmagssalik',
 'La Posada Hotel',
 'Comfort Stay Lodge',
 'Taloa Heights',
 'Angermeyer Waterfront Inn',
 'Swiss-Belinn Hotel Luwuk',
 'Sever Nadvoitsy',
 'Hotel New Palace',
 'Days Inn by Wyndham Paris',
 'Café de Upernavik',
 'Subhani Hotel',
 'Guest house Babinov',
 'The Crescent Hotel',
 'Talnakh Hotel',
 'Shanti Maurice Resort & Spa',
 'Jiatian International Hotel',
 'Hotel Torre Praia',
 'Hotel Devon',
 'La Hacienda Hotel',
 'Mercure Padang',
 'Hotel Route-Inn Noshiro',
 'Victoria Hotel - Bredasdorp',
 'Juman Hotel',
 nan,
 'Hotel Serra Verde',
 'The Ritz-Carlton, Half Moon Bay',
 nan,
 'Preskil Island Resort',
 'Hotel Ocean View & Restaurante Seafood',
 nan,
 nan,
 'Chukotka hotel',
 'Kindwitwi guesthouse',
 'Apart Hotel La Fuente',
 nan,
 'Quality Suites Vila Velha',
 'The Guesthouse at the Norwalk Inn',
 nan,
 'JJ Hotel',
 'Sofitel Rabat Jardin des Roses',
 'Nusa Island Retreat',
 'Lilin Lovina Beach Hotel',
 'Oa Oa Lodge',
 'Moinho do Poço Verde',
 'Super secret pirate cove',
 'Liduina Guest House',
 nan,
 'Chautauqua Harbor Hotel',
 'The Nantucket Hotel & Resort',
 'Best Western Thompson Hotel & Suites',
 nan,
 nan,
 'Pousada Kactus',
 'Panamericana Hotel Ancud',
 'Katsuura Hotel Mikazuki',
 'Prestige Hudson Bay Lodge',
 'Red Lion Hotel Coos Bay',
 'Bismillah Hotel And Lodging',
 nan,
 'Grand Naniloa Hotel Hilo - a DoubleTree by Hilton',
 'Hotel Hacienda Vieja',
 'Pond Country Club',
 'Hotel Trivento',
 'Hotel Tukums, Viesnīca Tukums',
 'Hotel Mehmon Saroy',
 nan,
 'Abha Palace Hotel',
 nan,
 'Hotel 2 Irmãos',
 'SpringHill Suites by Marriott Fairbanks',
 'Crest Hotel',
 nan,
 'Zleep Hotels',
 'Hotel da Canoa',
 "Pike's Waterfront Lodge",
 nan,
 'Radisson Blu Hotel, Dakar Sea Plaza',
 'Museum Hotel',
 'The Nest Hotel',
 'Oaks Hervey Bay Resort and Spa',
 nan,
 nan,
 'Seeadler Bay Hotel',
 'The Vic Boutique Hotel',
 'Altos de Güemes Hotel',
 "Bol'shaya Medveditsa",
 'OURE TERA beach resort',
 'Lakefront Lodge',
 'Oriental Ventura',
 'Courtyard by Marriott Waterloo St. Jacobs',
 'Qaanaaq Hotel',
 nan,
 'Ocean Centre Hotel',
 'Hostel At-Bashy',
 'Maritime Inn Antigonish',
 nan,
 'Best Western Nordlys Hotel Alta',
 'Hotel Kyriad Muraya',
 'Frobisher Inn',
 'Moli International Hotel',
 'Jinyuwan Hotel',
 nan,
 'ECO Lifestyle & Lodge',
 'DoubleTree by Hilton Panama City - El Carmen',
 nan,
 'Yalemd',
 nan,
 'Hôtel Restaurant Campanile Auch',
 'Desert Gardens Hotel - Ayers Rock Resort',
 nan,
 'Hotel Plaza Lebu',
 'Hyatt Regency Monterey Hotel And Spa On Del Monte Golf Course',
 'Opuwo Country Lodge',
 "Hunter's B&B",
 'Fortune Resort Bay Island',
 'Империя',
 '百名伽藍',
 nan,
 'ibis Hong Kong Central & Sheung Wan',
 'Vel-Kom',
 nan,
 'Nuli Sapi',
 'Zhang Ye Ding He Internationla Hotel',
 nan,
 'DoubleTree by Hilton Hotel Shiyan',
 'Hotel Boss',
 'Tui Base Camp',
 'Gostinitsa "Zapolyar\'ye"',
 nan,
 'Fiesta Inn Cuautitlan',
 'HYATT SALALAH HOTEL',
 'Fusaki Beach Resort Hotel & Villas',
 'Royal Kutachika Lodge',
 'The Grand Dragon Ladakh',
 'Pruksatara Garden',
 'Luwa Evergreen Hotel',
 'Steppe hotel',
 nan,
 'Qhini Hotel Boutique',
 'Kinwica',
 'Estalagem Da Ponta Do Sol',
 'Hôtel le Saint-Pierre',
 'Aspen Suites Hotel Sitka',
 nan,
 'Zeedijkresort',
 'Carrefour',
 'Garden Hotel',
 'Hotel ibis Styles Iu Namibe',
 'Hotel Patagonia',
 nan,
 'Holiday Inn Express & Suites Salinas',
 'Desert Palace Hotel & Casino Resort',
 'Hôtel Opémiska',
 "Casey's Inn Motor Hotel",
 'Kyriad Marvelous Hotel',
 'Tynwald Willow Bend Estate',
 'Hampton Inn by Hilton Elliot Lake, Ontario, Canada',
 nan,
 'Sofitel Legend Old Cataract Aswan',
 'Pousada Beira Mar Pitimbu Paraíba',
 nan,
 'Hotel Serrano',
 'Hampton Inn Danbury',
 nan,
 'St. George Inn & Suites',
 'Pebbles Inn',
 'Itacaiúnas Hotel',
 'Hotel Flasso 1',
 'いわない高原ホテル',
 nan,
 nan,
 nan,
 'Codrington Gardens Bed And Breakfast',
 'Auberge De La Chanterelle',
 nan,
 'Gostevoy Dom',
 'Hotel Playa El Cable',
 'Camp Ripan',
 nan,
 'Résidence OUADADA',
 'ibis Styles Boa Vista',
 'Hotel Meuligoe',
 'Arctic Chalet LTD',
 'La Maison Du Baron',
 'Kosmos',
 'Welcome Heritage Umed Bhawan Palace',
 'Bertelli Chuí Hotel',
 'Justfeeli Lodge, Luangwa',
 nan,
 'Sun Stay Kaseda',
 'The Grand Hotel Minneapolis',
 nan,
 'Villa del Mar Praia Hotel',
 'Hotel San Jorge Residencial',
 'Instow Barton',
 'Mystic Sands',
 'Hotel Pissoloto',
 'The Royal Grand Hotel',
 'Hotel Adler',
 'Hotel Las Brisas Acapulco',
 'Ulvesund FYR',
 nan,
 'Hotel de Casablanca',
 'Guest House HESADA',
 'Diamond Mountain Casino & Hotel',
 nan,
 'The Gilmore Hotel',
 'HOTEL ARAUJO',
 '7 Days Inn',
 'Pensiunea Sophia',
 'THE REDWOOD RIVERWALK HOTEL',
 'Sunset Beach Club',
 'House With 2 Bedrooms in Brenes, With Terrace and Wifi',
 nan,
 'Free Zone Hotel Nouadhibou',
 nan,
 'Dpravia Hotel',
 'HOTEL KIM ELISA',
 'Kingwood Hotel (Sibu) Sdn Bhd',
 nan,
 'Quality Suites',
 'Direct Hotels - Monterey Moranbah',
 'City Guest House Hotel',
 'Hilton Garden Inn Pascagoula',
 'Geiser Grand Hotel',
 'فندق جراند بالاس Grand Palace Hotel',
 nan,
 'Riyueming Hotel',
 nan,
 "Gostinyy Dvor Estel' Miniotel' V Severo-Yeniseyske",
 'Lakeview Hotel Motel',
 'Desert Gat',
 'Matho Crystal Hotel',
 'Tartous Grand Hotel',
 'Royal Hotel',
 'Embassy Suites by Hilton Columbia Greystone',
 'hotel sangam palace',
 'Hotel Porto Santo',
 'Lekota Spring Hotel',
 'Port Lincoln Hotel',
 'Hotel Элита',
 'Macdonald Houstoun House',
 'Hotel Qaqortoq',
 'Hilton Garden Inn Omaha West',
 'Gostinitsa Safari',
 'Hotel Noa Noa',
 'Bulls and Anchor Inn',
 'Blackwater Central Motel',
 'Sakhy Hotal Wah Mosafir Khana',
 'Hotel Olafsvik',
 'Hotel New Amami',
 nan,
 'Hotel Sole',
 'ibis Constantine',
 nan,
 'Shiny Motel',
 nan,
 nan,
 'Savoy Park Hotel',
 'Azor Hotel',
 'Húsavík Hotels',
 "Rhino's Nest",
 'Zhemchug',
 'Oceanaire Resort Hotel',
 'Hotel TerraSal',
 nan,
 'Pura Vida Bahia',
 nan,
 'Guest House on Kooperativnaya',
 'Hampton Inn & Suites Farmington',
 'فندق عرب بلازا',
 'Waterloo Guest House',
 'Mujo Suites',
 nan,
 'City Hotel',
 'Sri laxmi lodge',
 'Wifstavarfs Herrgård',
 '柏联SPA温泉',
 'Hotel Hans Egede',
 'AmericInn by Wyndham Cody',
 'ACHILLES HILL HOTEL',
 'Sundog Inn',
 'Bo Khin Guest House',
 'Budget Guesthouse Borgustova',
 'Distinction Dunedin Hotel',
 'Guest house Grushanka',
 'Seri Malaysia Mersing',
 'Embassy Suites by Hilton Lompoc Central Coast',
 'Nordkapp Vandrerhjem',
 'Vestmanna Hostel',
 'Swiss Belhotel Manokwari',
 'Motel La Banio',
 'Hotel Supremo',
 'KAROOFOUNTAIN LUXURY GUESTHOUSE',
 'Endless Summer Lodge - BBH',
 'Fiume Lodge',
 'Abacus Motel',
 'Hotel Solaris',
 'Holiday Inn Express & Suites Glendive',
 "Hotel D'Ewo",
 nan,
 'Maqna Hotel by Prasanthi',
 'Whitsunday Sands Resort',
 'Atlântida Mar Hotel',
 'The Cornwall Historic Hotel',
 'The Olive Exclusive All-Suite Hotel',
 nan,
 nan,
 'Gostinitsa Tamasha',
 'Varlıbaş Uyku Sarayı',
 'Grand Hôtel de Dolisie',
 'Hotel Bagoeira',
 'Hampton Inn & Suites Harvey/New Orleans West Bank, LA',
 'OYO 515 Oasis Hotel',
 'Zajazd Pod Skałą - hotel i restauracja',
 'Hotel Victori',
 'Hotel',
 'Hilton Hawaiian Village Waikiki Beach Resort',
 'Glen Lyon Inn',
 "Maison Vin d'Hus",
 'Avenida Park Hotel - Iturama - MG',
 'Hotel Miramar',
 'Hotel Cajoux',
 'Apartments in Inta city',
 'Cumberland Inn and Suites',
 'Namatanai Hotel',
 "L'oiseau de Paradis",
 nan,
 'Courtyard by Marriott Maui Kahului Airport',
 'The Harbour Inn',
 nan,
 'Odar kanawal',
 'Hotel Doña Marta',
 'Best Western Hoover Dam Hotel',
 'Noxapaga Suites',
 'Kimberley Anne Hotel',
 'Aspen Extended Stay Suites',
 nan,
 'Hotel Tamacá Beach Resort',
 nan,
 'Pousada Rio',
 'The majlis lamu hotel',
 'Gostinyy Dvor',
 'Palacio de La Villa',
 'Mehamn Arctic Hotel AS',
 nan,
 'Kokkolan Wanha Kartano',
 'Zilwa Attitude Hotel',
 'Motel Skazka',
 nan,
 'Lakeview Inns & Suites - Slave Lake',
 'Dhonfulhafi Beach View & Spa',
 'Ponta Anchaca',
 'Holiday Inn Nanyang',
 nan,
 'Riata Inn',
 nan,
 'Hotel Victori',
 'Chelpasin',
 'Hilton Zhoushan',
 'Hotel Indigo Mount Pleasant',
 nan,
 'Camaçari Plaza Hotel',
 'Hotel Grand Ashok',
 'Galle Fort Hotel',
 'Casa Grande de Anllo',
 'Ngare Sero Mountain Lodge',
 'Banjanay Hotel',
 'Amaloh Boutique Resort',
 'VITS Devbhumi, Dwarka',
 'Tarumã Tropical Hotel',
 'Shimane Hamada Washington Hotel Plaza',
 'Pazo do Souto',
 'Kak Doma',
 'Days Inn by Wyndham Easley West Of Greenville/Clemson Area',
 'West View Motel, Hanna, AB',
 'Tianyuan International Hotel',
 'Villa-Malaza',
 nan,
 'Hotel VIP Praia',
 nan,
 'La Vista Kushirogawa',
 'Hotel Beira Rio',
 'Pousada Estillos',
 'Arktika',
 nan,
 'Hotel El Raset',
 'Hotel Nordkyn',
 'Hotel Mapará Beach - Baião',
 'Royal Cashrise Lodge',
 nan,
 'Hotel Belle Vue',
 'Hotel Tuljai',
 'Hotel Y Restaurante Los Lapachos',
 'Hotel Europa Olympia',
 'MAKERS HOTEL',
 'Bugaendrus Paradise',
 'Skyways Guesthouse',
 'Red Lion Inn & Suites Grants Pass',
 'Copthorne Hotel Aberdeen',
 'Castillo de la Fantasia',
 'The Inn At Schofield',
 nan,
 'Çelikoğlu Otel Emirdağ',
 nan,
 'Hotel Karem Bay',
 nan,
 'Hampton Inn Ukiah',
 nan,
 'HOTEL R. SOARES',
 'Athabasca Lodge Motel',
 'Гостиница ВИОЛА',
 'Jinhai New Century Grand Hotel',
 'Nile Palace Hotel',
 'Hôtel Matagami',
 'Hotel Tamires',
 'Gidaan Guest House',
 'Tang Dynasty Lodge Kota Belud',
 'DoubleTree by Hilton Hotel Cairns',
 nan,
 nan,
 "Raven's Rest Inn",
 'Pousada da Floresta',
 nan,
 nan,
 'Finnsnes Hotel - A SNR Hotel',
 nan,
 'La visa hotel',
 "Ka'ana Resort And Spa",
 'Walkabout Lodge & Tavern',
 'Hotel Punta León',
 'Holiday Inn Express & Suites Elk Grove Central - Hwy 99',
 nan,
 'Hotel Nemuro Kaiyoutei',
 'Hotel Manolos',
 'Hotel Kargasok',
 'Lianzhou International Hotel',
 'Hotel Restaurant Gourmand Coco Lodge Majunga',
 'Les Lodges Vanilliers',
 nan,
 'Xinxin Hotel',
 'Hotel King Star',
 nan,
 nan,
 nan,
 'Shangri-La Hotel, Hohhot',
 'Hagi no Yado Tomoe',
 nan,
 'Hotel Zavala´S',
 'Hotel Grand Gaayathri',
 nan,
 nan,
 'TG Hotel',
 'Zenit San Sebastián',
 'Hotel Santa Cruz',
 'Kuruman Inn by Country Hotels',
 'Dhukurrdji Lodge',
 'Radisson Hotel Duluth-Harborview',
 'Hotel Voyage',
 nan,
 'Protea Hotel by Marriott Walvis Bay Pelican Bay',
 nan,
 '哈密环球大酒店',
 nan,
 'ささやかなおうち串間/高松(貸別荘)',
 'Hotel Boutique',
 'Grand Central Hotel',
 'Yeppoon Beach House',
 'Holy Drop Skate House',
 'Sofitel Marrakech Lounge & Spa',
 'Tanjung Kodok Beach Resort',
 'Gostinnitsa Medveditsa',
 'Astorga Park Hotel',
 'Uyutnaya Mini-Hotel',
 'Curubo Hotel',
 'Hotel Gemstone Inn']

In [9]:
hotel_df['Hotel Name']= hotel_name
hotel_df.dropna()
#hotel_df.to_csv('hotel_export.csv')

          City Country  Latitude  Longitude                  Hotel Name
0       Narsaq      GL     60.92     -46.05            Igdlo Guesthouse
1      Ushuaia      AR    -54.80     -68.30  Los Cauquenes Resort & Spa
2        Rocha      UY    -34.48     -54.33             Beleza Pura B&B
3       Atuona      PF     -9.80    -139.03        Simplicité Marquises
4         Rome      US     43.21     -75.46     Wingate By Wyndham Rome
..         ...     ...       ...        ...                         ...
542    Urengoy      RU     65.97      78.37      Gostinnitsa Medveditsa
543    Astorga      BR    -23.23     -51.67          Astorga Park Hotel
544  Kyshtovka      RU     56.55      76.63         Uyutnaya Mini-Hotel
545    Garoowe      SO      8.41      48.48                Curubo Hotel
546   El Tigre      VE      8.89     -64.25          Hotel Gemstone Inn

[439 rows x 5 columns]

In [10]:
# NOTE: Do not change any of the code in this cell

# Using the template add the hotel marks to the heatmap
info_box_template = """
<dl>
<dt>Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
</dl>
"""
# Store the DataFrame Row
hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]
locations = hotel_df[["Latitude", "Longitude"]]

In [11]:
# Add marker layer ontop of heat map
markers = gmaps.marker_layer(locations)
fig.add_layer(markers)

# Display figure
fig

Figure(layout=FigureLayout(height='420px'))